### ISSUE TITLE
Add IE7 support

### ISSUE THREAD

**Issue by fdaugan** [jaridmargolin/formatter.js#11]
On IE7, no Javascript error, and the typed text is not visible.
Even the initialized text by html value is not visible.
Works well on IE8.

Tested on master and the 5 days ago masters's version.
jquery version : 1.8.3

**Comment by jaridmargolin** [comment]
I will investigate. At the very least, if I find it not possible to support IE7, the inputs need to still be usable. Thank you.

**Comment by fdaugan** [comment]
It works like a charm :)
