### ISSUE TITLE
Several keys' behavior overridden by the library causing usability issues

### ISSUE THREAD

**Issue by scunliffe** [jaridmargolin/formatter.js#2]
The formatting options are great... but as a user it bugs me that the usability of the text fields have been compromised as a result of the library.

For example the arrow keys (left, right) no longer navigate within the text field should the user want to correct a typo.

The delete key (on a PC) should "erase" characters to the right of the cursor/caret yet currently erases characters to the left like a backspace key.

The shift key has been disabled so manually selecting multiple characters to delete/type over is not possible.

The Home key does not take the user's cursor/caret to the beginning of the field/line... nor does the End key take the user to the end of the field/line.

**Comment by jaridmargolin** [comment]
Thank you for raising these issues. Tests were implemented using an apple keyboard configuration. I will have to strengthen tests for alternate configurations (PC).

All points raised and valid and will be addressed as soon as possible.

Do you mind providing me with your exact OS / Browser?

**Comment by scunliffe** [comment]
Thanks Jarid... yeah I'm on a PC (Windows 7) running Firefox 24 (but I can test in any other Windows based browser if you like to confirm if these are global beyond Firefox).

**Comment by jaridmargolin** [comment]
This actually appears to be 2 separate issues:
1. Issue #4 - In Mozilla arrow keys trigger keypress
2. PC specific keys (Home, End, and Delete key)

Please confirm. Shift and arrow keys should be working.
http://firstopinion.github.io/formatter.js/demos.html

**Comment by scunliffe** [comment]
Yes, the shift and arrow keys are working now on Windows in (Firefox, Chrome, Opera, & IE) - thanks!
