### ISSUE TITLE
Allow Caps Enforcement

### ISSUE THREAD

**Issue by joshvickerson** [jaridmargolin/formatter.js#24]
Would it be possible to implement forced capitalization in patterns? Specifying 'A' instead of 'a' for auto capitalization, for example?

**Comment by jaridmargolin** [comment]
There is now a method `addInptType`. It allows for creation of new input types for use in patterns.

**Example:**

```
Formatter.addInptType('L', /[A-Z]/);

new Formatter({
  pattern: '{{LL}}'
});
```
