### ISSUE TITLE
Wrong minified versions

### ISSUE THREAD

**Issue by sylido** [jaridmargolin/formatter.js#41]
The unminified version of formatter.js are fine, but the minified ones are using "require" - both the jquery and non-jquery versions are affected. The un-minified versions work just fine after getting minified/uglified.

**Comment by kirkhansen** [comment]
I also had trouble with this. Thanks for pointing this out for everybody.

**Comment by jaridmargolin** [comment]
Addressed in v0.1.0. Thank you for submitting.
