### ISSUE TITLE
Doesn't work on phones (android)

### ISSUE THREAD

**Issue by awudarowicz** [jaridmargolin/formatter.js#42]
You have tried to test it on mobile phone? It completely doesn't work..

**Comment by mckaythomas** [comment]
What device are you using? What browser? In what ways was it not working?

It was actually originally created for mobile devices, so there must be something about your situation that is breaking it. I hope we can get to the bottom of this. 

—
McKay

No waiting rooms, just text a doctor.
http://FirstOpinionApp.com

**Comment by th0r** [comment]
Text deleting is buggy in latest Chrome Mobile (version 34).
Formatter version is 0.0.9

**Comment by jaridmargolin** [comment]
@thor - If you would like to open a new ticket specifying what exactly is 'buggy', I would be happy to investigate.

@nokunpl - I am closing this issue as you have provided no reproducible steps or environment information.

**Comment by thor** [comment]
@jaridmargolin I think you wanted to get @th0r's attention, not mine! :)
