### ISSUE TITLE
Moving focus using `tab` key is not working

### ISSUE THREAD

**Issue by th0r** [jaridmargolin/formatter.js#44]
When focus is on formatted input pressing `tab` key doesn't move focus to the next form field.
Formatter version is 0.0.9

**Comment by Abbe98** [comment]
Works in latest Opera and Chrome(the only browsers I tested)...

**Comment by th0r** [comment]
Oh, forgot to say - browser is Firefox 28.

**Comment by jaridmargolin** [comment]
Using Firefox 28 on OSX with no issues. Perhaps this is related to OS and not browser?

**Comment by Abbe98** [comment]
I just tried it in Firefox 28 on Windows and I can't reproduce the issue...

I can't see that the issue is related to formatter at all...

**Comment by jaridmargolin** [comment]
Thank you @Abbe98.

@th0r - Will open if you can provide reproducible steps.

**Comment by th0r** [comment]
Version `0.1.4` don't have this bug. Thanks!
