### ISSUE TITLE
document.selection.createRange() causes errors in Chrome

### ISSUE THREAD

**Issue by TSchuermans** [jaridmargolin/formatter.js#50]
Error occurred in chrome 35.0.1916.114 on mac os x 10.9.3
Error: Uncaught TypeError: Cannot read property 'createRange' of undefined.

Probably a bug in Chrome, works in firefox and safari.

**Comment by capan** [comment]
Hi, @TSchuermans have you found a fix for the problem ?

**Comment by TSchuermans** [comment]
I don't know :(
It's been 5+ years ago, so I can't remember.
Sorry!

**Comment by capan** [comment]
At least I have tried  ! thanks
