### ISSUE TITLE
jQuery input event suppressed

### ISSUE THREAD

**Issue by popko** [jaridmargolin/formatter.js#52]
Enabling formatter for example in an input element prevents to fire jQuery input event on that particular element. I consider this a bug.

**Comment by joshminnie** [comment]
+1

I'm experiencing the same thing.

**Comment by jaridmargolin** [comment]
I consider it a bug as well. I will investigate when time permits.

**Comment by gmanley** [comment]
I solved this by adding:

``` javascript

      if ('createEvent' in document) {
        var evt = document.createEvent('HTMLEvents');
        evt.initEvent('input', true, true);
        this.el.dispatchEvent(evt);
      } else {
        this.el.fireEvent('oninput');
      }
```

to line 694 of merged source or https://github.com/firstopinion/formatter.js/blob/master/src/formatter.js#L317. Definitely just a temporary fix. It will work in IE8+.

**Comment by vialcollet** [comment]
@gmanley Thanks. This is solving the issue on using formatter.js in AngularJS.

**Comment by popko** [comment]
Thanks @gmanley
