### ISSUE TITLE
Format time field (HH:MM)

### ISSUE THREAD

**Issue by deaser** [jaridmargolin/formatter.js#53]
How can I mask input to accept only 24-hour format? I've tried something like:
new Formatter(timeElems[i], {
                    'pattern': '{{99}}:{{99}}',
                    'persistent': false,
                    'patterns':[
                        { '^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$': 'time: {{*****}}' }
                    ]
                });

but it doesn't work at all.

**Comment by jaridmargolin** [comment]
This question would be more suited for a platform such as stackoverflow. I would like to keep issues primarily for bug fixes / feature requests.

Best of luck.
