### ISSUE TITLE
Plain formatting

### ISSUE THREAD

**Issue by andreyvital** [jaridmargolin/formatter.js#65]
can I use this outside of a node?

&ndash; goal:

``` JS
var formatted = new Formatter('123123123', '({999}) - ({999}, {999})'); // (123) - (123, 123)
```

There's any way to reach this?
Thanks.

**Comment by jaridmargolin** [comment]
The library was not built for this use case.

If desired, you could use a hidden element and simply grab the formatted value from it?

**Comment by andreyvital** [comment]
@jaridmargolin yes, but I already solved.
